version: "3.1" 
services:
  dovecot:
    image: thehelpfulidiot/dovecot:latest
    container_name: dovecot
    ports:
      - "993:993"
    volumes:
      - /path/to/ssl:/ssl
      - /path/to/mail:/mail
      - /path/to/logs:/var/log/dovecot
    environment:
      - email_username=bob
      - email_password=odenkirk
      - PUID=1000
      - disable_plaintext_auth=no
      - ssl_cert=cert1.pem
      - ssl_key=privkey1.pem
      - ssl=required
      - server_address=imap.home.local
  mbsync:
    image: thehelpfulidiot/mbsync:latest
    container_name: mbsync
    volumes:
      - /path/to/mail:/mail
    environment:
      - host_name=server
      - port=port
      - remote_username=username
      - remote_password=password
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=gmail
      - PUID=1000
