services:
  dovecot:
    image: thehelpfulidiot/dovecot:latest
    container_name: dovecot
    restart: always
    ports:
      - "993:993"
      - "143:143"
    volumes:
      - /path/to/ssl:/ssl
      - /path/to/mail:/mail # same as mbsync
      - /path/to/logs:/var/log/dovecot
    environment:
      - email_username=bob
      - email_password=odenkirk
      - PUID=1000
      - disable_plaintext_auth=no
      - ssl_cert=cert.pem
      - ssl_key=key.pem
      - ssl=required
      - server_address=imap.home.local
      - dh_pem=yes
      
  mbsync:
    image: thehelpfulidiot/mbsync:latest
    container_name: mbsync
    restart: always
    volumes:
      - /path/to/mail:/mail # same as dovecot
    environment:
      - host_name=server
      - port=port
      - remote_username=username
      - remote_password=password
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=gmail
      - PUID=1000
      - cron=yes

  solr:
    image: thehelpfulidiot/solr:latest
    container_name: solr
#    ports:
#      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    restart: always

volumes:
  solr-data:


  
